### PR TITLE
Hopefully this works.

### PR DESCRIPTION
**Pull request by 6100m**

### CODE REVIEW

**Comment by 6100m** [comment]
@spotlightishere @zurgeg Can you both merge this in CLI?

**Comment by zurgeg** [comment]
Sure.

**Comment by 6100m** [comment]
Also, I have changed the name to WIiCron24, sorry if it desynced for a second. Honestly, I like WiiCron24 name a bit better actually :)

**Comment by zurgeg** [comment]
Force merged in desktop.

**Pull request closed without merging**
